/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Shadcn_neutralIndexRouteImport } from './routes/shadcn_neutral/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Shadcn_neutralIndexRoute = Shadcn_neutralIndexRouteImport.update({
  id: '/shadcn_neutral/',
  path: '/shadcn_neutral/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shadcn_neutral': typeof Shadcn_neutralIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shadcn_neutral': typeof Shadcn_neutralIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shadcn_neutral/': typeof Shadcn_neutralIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/shadcn_neutral'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/shadcn_neutral'
  id: '__root__' | '/' | '/shadcn_neutral/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Shadcn_neutralIndexRoute: typeof Shadcn_neutralIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shadcn_neutral/': {
      id: '/shadcn_neutral/'
      path: '/shadcn_neutral'
      fullPath: '/shadcn_neutral'
      preLoaderRoute: typeof Shadcn_neutralIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Shadcn_neutralIndexRoute: Shadcn_neutralIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
