substitutions:
  _NODE_IMAGE: 'node:22.14.0-alpine'
  _PROJECT_NAME: '20250530_sandbox_example_nextjs'
  _REGION: 'asia-northeast1'
  _REPOSITORY_NAME: '20250530_sandbox_example_nextjs'  # ← Artifact Registry のリポジトリ名
  _CONTAINER_NAME: '20250530_sandbox_example_nextjs'

steps:
  - name: '$_NODE_IMAGE'
    id: Install dependencies
    entrypoint: sh
    dir: '.'
    args:
      - '-c'
      - |
        if [ -d ".cache/node_modules" ]; then
          echo "Restoring node_modules from cache..."
          cp -r .cache/node_modules ./node_modules
        fi

        echo "Installing dependencies..."
        npm ci

        echo "Saving node_modules to cache..."
        mkdir -p .cache
        cp -r node_modules .cache/node_modules

    volumes:
      - name: npm-cache
        path: /workspace/.cache

  - name: '$_NODE_IMAGE'
    id: Build with Next.js
    dir: '.'
    entrypoint: sh
    args:
      - '-c'
      - |
        echo "Restoring .next/cache if available..."
        if [ -d ".next-cache" ]; then
          mkdir -p .next/cache
          cp -r .next-cache/* .next/cache/ || true
        fi

        npm run build

        echo "Caching .next/cache..."
        if [ -d .next/cache ]; then
          cp -r .next/cache .next-cache
        fi

    volumes:
      - name: next-cache
        path: /workspace/.next-cache
    env:
      - NODE_ENV=production

  - name: 'gcr.io/cloud-builders/docker'
    id: Build and Push Image
    dir: '.'
    args: [
      'build',
      '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY_NAME/$BRANCH_NAME-$_CONTAINER_NAME:latest',
      '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY_NAME/$BRANCH_NAME-$_CONTAINER_NAME:$COMMIT_SHA',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: Docker Push
    args: [
      'push',
      '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY_NAME/$BRANCH_NAME-$_CONTAINER_NAME:latest'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: Docker Push
    args: [
      'push',
      '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY_NAME/$BRANCH_NAME-$_CONTAINER_NAME:$COMMIT_SHA'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy to Cloud Run
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "Branch: $BRANCH_NAME"

        if [[ "$BRANCH_NAME" =~ ^(launch|launch2|dev01|dev02|demo|stress)$ ]]; then
          gcloud run deploy $_CONTAINER_NAME \
            --image $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY_NAME/$BRANCH_NAME-$_CONTAINER_NAME:latest \
            --region $_REGION \
            --platform managed \
            --allow-unauthenticated \
            --port 3000 \
            --update-secrets=NEXTAUTH_SECRET=NEXTAUTH_SECRET:latest
        else
          echo "Skipping deployment for branch: $BRANCH_NAME"
        fi

images:
  - 'gcr.io/$PROJECT_ID/$_PROJECT_NAME'

options:
  volumes:
    - name: npm-cache
      path: /workspace/.cache
    - name: next-cache
      path: /workspace/.next-cache
