substitutions:
  _PROJECT_NAME: 'sandbox-example-nextjs'
  _REGION: 'asia-northeast1'
  _REPOSITORY_NAME: 'sandbox-example-nextjs'  # ← Artifact Registry のリポジトリ名
  _CONTAINER_NAME: 'sandbox-example-nextjs'
  _BRANCH_NAME: $BRANCH_NAME
  _COMMIT_SHA: $COMMIT_SHA

steps:
  - name: gcr.io/cloud-builders/gsutil
    id: 'download-next-cache'
    entrypoint: bash
    args:
      - '-c'
      - |
        gsutil cp gs://${_PROJECT_NAME}/${_BRANCH_NAME}/next_cache.tar.gz next_cache.tar.gz || echo "No cache found, skipping..."
  - name: bash
    id: 'extract-next-cache'
    entrypoint: bash
    args:
      - '-c'
      - |
        if [ -f next_cache.tar.gz ]; then
          echo "Extracting next_cache.tar.gz..."
          tar xzf next_cache.tar.gz
        else
          echo "No cache archive to extract"
        fi

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        set -e
        docker build \
          -t $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY_NAME/$_BRANCH_NAME-$_CONTAINER_NAME:$_COMMIT_SHA \
          -t $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY_NAME/$_BRANCH_NAME-$_CONTAINER_NAME:latest \
          -t sandbox-example-nextjs \
          -f Dockerfile \
          --build-arg BRANCH_NAME=$BRANCH_NAME \
          .
        docker run --name sandbox-example-nextjs -d sandbox-example-nextjs

        mkdir -p .next
        docker cp sandbox-example-nextjs:/app/.next/cache .next/cache

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY_NAME/$_BRANCH_NAME-$_CONTAINER_NAME:latest'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY_NAME/$_BRANCH_NAME-$_CONTAINER_NAME:$_COMMIT_SHA'
    ]

  - name: bash
    id: 'archive next_cache'
    args: ['tar', 'czf', 'next_cache.tar.gz', '.next/cache']
  # upload
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'next_cache.tar.gz', 'gs://${_PROJECT_NAME}/${_BRANCH_NAME}/next_cache.tar.gz']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy to Cloud Run
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "Branch: $_BRANCH_NAME"

        if [[ "$_BRANCH_NAME" =~ ^(launch|launch2|dev01|dev02|demo|stress)$ ]]; then
          gcloud run deploy $_CONTAINER_NAME \
            --image $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY_NAME/$_BRANCH_NAME-$_CONTAINER_NAME:latest \
            --region $_REGION \
            --platform managed \
            --allow-unauthenticated \
            --port 3000 \
            --update-secrets=NEXTAUTH_SECRET=NEXTAUTH_SECRET:latest
        else
          echo "Skipping deployment for branch: $_BRANCH_NAME"
        fi
