import type {
  Metadata,
} from 'next';

import './globals.css';
// import 'shadcn_neutral/index.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function ShadcnNeutralLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return children;
}
